name: IF manifest computation

on:
  push:
    branches:
      - gh-pages
    paths-ignore:
      - 'dist/**'

jobs:
  build:
    env:
      CI_COMMIT_MESSAGE: Continuous Integration Build Artifacts
      CI_COMMIT_AUTHOR: Continuous Integration
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build project for production
        run: |
          npm ci
          npm run build-prod

      - name: commit & push

        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "username@users.noreply.github.com"
          git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}"
          git push
